name: Lint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true
    - run: bundle exec danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
